# Generated by Django 5.2.8 on 2025-12-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_time'], 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats_count',
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='Подтверждено'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('number', models.IntegerField(verbose_name='Номер места')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='cinema.seat', verbose_name='Забронированные места'),
        ),
    ]
